### ISSUE TITLE
[Error] A java error occurred in the main process

### ISSUE THREAD

**Issue by Terkyz** [SixGrid/sixgrid#23] opened 2024-01-27 19:37 UTC
Hi! I've installed Sixgrind through AUR, and when I open it I always have this error... I also tried to run the appimage, but it gave me the same error.

![screenshot-20240127-193206Z-current](https://github.com/SixGrid/sixgrid/assets/102398589/a9ae58ff-30c0-4dbc-ac24-eb8353de6aa5)

**Comment by ktwrd** [comment] 2024-01-28 02:00
The sixgrid app on the AUR is not supported since I cannot maintain it (I do not have Arch and I don't know who published it there).

Please download an AppImage from the Releases tab or join the discord server (and dm me) for a steam key.

**Comment by Terkyz** [comment] 2024-01-28 19:34
I keep having the same error with the appimage, and I don't use Discord. :(

**Comment by ktwrd** [comment] 2024-01-29 12:35
I'll look into fixing the AppImage tomorrow after work.

Have you tried using the portable version? (`*linux-amd64.tar.gz` or `*linux-amd64.zip`)

**Comment by Terkyz** [comment] 2024-01-29 12:56
Yes, unfortunate I keep having the same error.

I even installed a Windows 10 VM in Qemu and tried running the .msi, but it gave the same error.

**Comment by ktwrd** [comment] 2024-01-29 13:18
Trying to work on a fix atm. I'm using WSL at the moment to try and get a fix (since I do not have access to my Linux machine atm) but the unpacked version works.

Does this AppImage work?
https://res.kate.pet/upload/7a33ff559895/sixgrid-0.3.7-2.AppImage

**Comment by ktwrd** [comment] 2024-01-29 13:21
> I even installed a Windows 10 VM in Qemu and tried running the .msi, but it gave the same error.

Fixed this issue by adding setting `build.asar` to `true` in `package.json`.

**Comment by Terkyz** [comment] 2024-01-29 13:24
> Trying to work on a fix atm. I'm using WSL at the moment to try and get a fix (since I do not have access to my Linux machine atm) but the unpacked version works.
> 
> Does this AppImage work? https://res.kate.pet/upload/7a33ff559895/sixgrid-0.3.7-2.AppImage

It opens but it's just a [white screen](https://imgur.com/a/36R4Bd5), here are the logs from my terminal:

```
(node:3403) Electron: Loading non-context-aware native module in renderer: '/tmp/.mount_sixgriHqiYyN/resources/app/node_modules/greenworks/lib/greenworks-linux64.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
before-input-event meta { relaunch: 'F10', debugOutline: 'F9', safeReload: 'F8' }
before-input-event shift { relaunch: 'F10', debugOutline: 'F9', safeReload: 'F8' }
before-input-event shift { relaunch: 'F10', debugOutline: 'F9', safeReload: 'F8' }
before-input-event meta { relaunch: 'F10', debugOutline: 'F9', safeReload: 'F8' }
(node:3454) Electron: Loading non-context-aware native module in renderer: '/tmp/.mount_sixgriHqiYyN/resources/app/node_modules/greenworks/lib/greenworks-linux64.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
before-input-event meta { relaunch: 'F10', debugOutline: 'F9', safeReload: 'F8' }
before-input-event meta { relaunch: 'F10', debugOutline: 'F9', safeReload: 'F8' }
```

**Comment by ktwrd** [comment] 2024-01-29 13:26
I'm getting the same issue and I'm looking into it rn.

**Comment by ktwrd** [comment] 2024-01-29 13:44
Might be related, but there are a lot of things to update from Electron 11 to the latest version.
Tried doing it previously last year and it broke everything.

https://github.com/electron/electron/issues/2357#issuecomment-1802210380

I will try to release a hotfix tonight for non-AppImage versions, but a fix for the AppImage release will have to wait for when I have spare time.

**Comment by ktwrd** [comment] 2024-01-30 13:28
Fixed it :3

![screenshot](https://res.kate.pet/upload/bdf2c29b53e3/msrdc_eltgzOAE1p.png)

Use release [20240130-03](https://github.com/SixGrid/sixgrid/releases/tag/20240130-03) until I make a proper release tomorrow :3

**Comment by Terkyz** [comment] 2024-01-30 14:44
I tried running both the .appimage (although you already said that you'll fix it when you have more time) and the linux-amd64.tar.gz and I keep having a white screen, although this time the log from the terminal is different.

Edit: I do have Electron installed.

```

/home/arco/Downloads/sixgrid
(node:19346) electron: Failed to load URL: file:///home/arco/Downloads/resources/app/dist/electron/index.html with error: ERR_FILE_NOT_FOUND
(Use `sixgrid --trace-warnings ...` to show where the warning was created)
```

![screenshot-20240130-144249Z-all](https://github.com/SixGrid/sixgrid/assets/102398589/6883d1c7-8669-40a8-9bfc-b56755cc4b20)

**Comment by Terkyz** [comment] 2024-01-30 16:04
So, I tried in my laptop with ArcoLinuxB Sway, and my desktop use ArcoLinuxB i3 and the result it's the same.
![2024-01-30T10:03:21,304305913-06:00](https://github.com/SixGrid/sixgrid/assets/102398589/1d846585-9670-443f-ae60-cec55078b377)

**Comment by ktwrd** [comment] 2024-01-31 23:19
Can you click on "View" then "Toggle Developer Tools" in the menubar?

Also have you tried running with `--disable-gpu` (since it can cause some issues with rendering)

**Comment by Terkyz** [comment] 2024-02-01 00:17
Yes, I can click it but seems that there's nothing to show for some reason.
![2024-01-31T18:15:35,385286726-06:00](https://github.com/SixGrid/sixgrid/assets/102398589/26b970f6-8551-4351-947c-6562ee3d135f)

And with `--disable-gpu` nothing happens...
![2024-01-31T18:16:46,833381429-06:00](https://github.com/SixGrid/sixgrid/assets/102398589/ad4743b1-75e6-4a85-91bc-2f83927503f5)

**Comment by ktwrd** [comment] 2024-02-03 07:06
Can you send a screenshot of the console tab so I can see whatever exception is being thrown?

**Comment by Terkyz** [comment] 2024-02-04 21:57
![screenshot-20240204-215724Z-all](https://github.com/SixGrid/sixgrid/assets/102398589/cf616da9-868b-4e64-a9bd-f87848eaa952)

**Comment by Terkyz** [comment] 2024-02-04 21:59
![screenshot-20240204-215906Z-all](https://github.com/SixGrid/sixgrid/assets/102398589/84f00d81-8259-4047-93d6-d6d0f636a7c4)

**Comment by ktwrd** [comment] 2024-02-05 12:35
In the console of the devtools, can you send the output of `console.log(window.location.toString())` and `JSON.stringify(process.env)`

**Comment by Terkyz** [comment] 2024-02-05 14:09
> console.log(window.location.toString())

`No resource with given URL found`

> JSON.stringify(process.env)

`{"SHELL":"/bin/bash","WINDOWID":"44040195","COLORTERM":"truecolor","XDG_SESSION_PATH":"/org/freedesktop/DisplayManager/Session0","HISTCONTROL":"ignoreboth:erasedups","I3SOCK":"/run/user/1000/i3/ipc-socket.1241","LC_ADDRESS":"es_CR.UTF-8","LC_NAME":"es_CR.UTF-8","DESKTOP_SESSION":"i3","LC_MONETARY":"es_CR.UTF-8","EDITOR":"nano","GTK_MODULES":"canberra-gtk-module","XDG_SEAT":"seat0","PWD":"/home/arco/Downloads","XDG_SESSION_DESKTOP":"i3","LOGNAME":"arco","QT_QPA_PLATFORMTHEME":"qt5ct","XDG_SESSION_TYPE":"x11","XAUTHORITY":"/home/arco/.Xauthority","XDG_GREETER_DATA_DIR":"/var/lib/lightdm-data/arco","QT_STYLE_OVERRIDE":"kvantum","MOTD_SHOWN":"pam","HOME":"/home/arco","LC_PAPER":"es_CR.UTF-8","LANG":"en_US.UTF-8","XDG_CURRENT_DESKTOP":"i3","XDG_SEAT_PATH":"/org/freedesktop/DisplayManager/Seat0","ALACRITTY_SOCKET":"/run/user/1000/Alacritty-:0-8826.sock","XDG_SESSION_CLASS":"user","TERM":"alacritty","LC_IDENTIFICATION":"es_CR.UTF-8","USER":"arco","VISUAL":"nano","DISPLAY":":0","SHLVL":"0","PAGER":"most","LC_TELEPHONE":"es_CR.UTF-8","LC_MEASUREMENT":"es_CR.UTF-8","XDG_VTNR":"7","XDG_SESSION_ID":"2","XDG_RUNTIME_DIR":"/run/user/1000","DEBUGINFOD_URLS":"https://debuginfod.archlinux.org ","LC_TIME":"es_CR.UTF-8","GTK3_MODULES":"xapp-gtk3-module","XDG_DATA_DIRS":"/home/arco/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop","BROWSER":"firefox","PATH":"/home/arco/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/var/lib/flatpak/exports/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin","ALACRITTY_LOG":"/tmp/Alacritty-8826.log","GDMSESSION":"i3","DBUS_SESSION_BUS_ADDRESS":"unix:path=/run/user/1000/bus","MAIL":"/var/spool/mail/arco","ALACRITTY_WINDOW_ID":"44040195","LC_NUMERIC":"es_CR.UTF-8","OLDPWD":"/home/arco","_":"./sixgrid","CHROME_DESKTOP":"sixgrid.desktop","ORIGINAL_XDG_CURRENT_DESKTOP":"i3","GDK_BACKEND":"x11","NO_AT_BRIDGE":"1"}`

**Comment by Terkyz** [comment] 2024-02-05 15:05
So I installed a clean KDE Neon VM in Qemu and I keep having the white screen issue, it may be obvious but I tried it because I don't know, it may be related to the framework that i3 uses to draw the windows widgets on screen

**Comment by ktwrd** [comment] 2024-02-06 06:35
> So I installed a clean KDE Neon VM in Qemu and I keep having the white screen issue, it may be obvious but I tried it because I don't know, it may be related to the framework that i3 uses to draw the windows widgets on screen

Seems like it's a skill issue on my end with Electron actually locating the `index.html` file. Not sure why this is happening but I'm fairly sure it is a simple fix. I'll look into it when I get home after work.

For now, use the following bash script (but replace `/location/to/sixgrid` to the directory where the `sixgrid` executable exists)
```bash
#!/bin/bash
cd /location/to/sixgrid
./sixgrid
```

**Comment by ktwrd** [comment] 2024-02-06 10:20
@Terkyz I reproduced the issue, fixed it. Linux builds should be fixed (zip/tar and appimage).

https://github.com/SixGrid/sixgrid/releases/tag/20240206

**Comment by Terkyz** [comment] 2024-02-06 14:15
Now it's working perfectly, thanks your working on the fix!

I should open Issues to request features?

**Comment by ktwrd** [comment] 2024-02-07 01:44
> Now it's working perfectly, thanks your working on the fix!
>

Fuck yeah!!!

> I should open Issues to request features?
>

Yes please, that would be great!

**Closed as completed** 2024-02-07 01:44 UTC
Labels: bug, AUR (Unsupported)
